#!/usr/bin/env bash
# Train one model configuration across five seeds.
#
# Five seeds is not decoration. The paper's argument rests on being able to say
# whether a difference between models is larger than the noise between runs, and
# a single training run cannot answer that.
#
# How it works: Pointcept's own scripts/train.sh takes no extra command-line
# options (its getopts handles only p d c n w g m r). Rather than patch someone
# else's script, we GENERATE one derived config per seed containing nothing but
# `_base_` pointing at the parent config plus `seed = N`. Useful side effect for
# reproducibility: every run leaves its own config on disk.
#
#   ./train_seeds.sh semseg-ptv3-pheno4d-maize-noflash 1
set -euo pipefail

CFG=${1:?usage: train_seeds.sh <config-name-without-.py> [num_gpu]}

# W&B off: Tensorboard already logs everything to exp/. Without these two lines
# Pointcept raises an interactive login prompt that hangs the process indefinitely
# -- fatal for a sequence left running unattended.
export WANDB_MODE=${WANDB_MODE:-disabled}
export WANDB_SILENT=true

NGPU=${2:-1}
SEEDS=(0 1 2 3 4)
POINTCEPT=${POINTCEPT:-$HOME/G2/Pointcept}
CFGDIR="$POINTCEPT/configs/pheno4d"

[ -f "$CFGDIR/${CFG}.py" ] || { echo "no such config: $CFGDIR/${CFG}.py"; exit 1; }

cd "$POINTCEPT"
for S in "${SEEDS[@]}"; do
  EXP="${CFG}-seed${S}"
  if [ -f "exp/pheno4d/${EXP}/model/model_best.pth" ]; then
    echo "== skipping ${EXP} (model_best.pth already present)"; continue
  fi

  # derived config: overrides the seed and nothing else
  cat > "$CFGDIR/${EXP}.py" <<EOF
# Generated by train_seeds.sh -- do not edit by hand.
_base_ = ["./${CFG}.py"]
seed = ${S}
EOF

  echo "══════════════════════════════════════ ${EXP}"
  sh scripts/train.sh -g "$NGPU" -d pheno4d -c "$EXP" -n "$EXP"
done

echo; echo "done. results in ${POINTCEPT}/exp/pheno4d/"
echo "check which seeds were actually used:"
echo "  grep -h '^seed' ${POINTCEPT}/exp/pheno4d/${CFG}-seed*/config.py"
